##################################################################################################################
# helm template memcached bitnami/memcached --version 6.7.2 --kube-version 1.28.3 -f values.yaml > manifest.yaml #
# ref: https://artifacthub.io/packages/helm/bitnami/memcached                                                    #
##################################################################################################################

# apiVersion: v1
# kind: Service
# metadata:
#   name: memcached-service
# spec:
#   type: NodePort
#   ports:
#   - port: 11211
#     targetPort: 11211
#     nodePort: 30053
#     protocol: TCP
#     selector:
#       app.kubernetes.io/instance: memcached
#       app.kubernetes.io/name: memcached


# Source: memcached/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: default
  labels:
    app.kubernetes.io/instance: memcached
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcached
    app.kubernetes.io/version: 1.6.22
    helm.sh/chart: memcached-6.7.1
spec:
  type: ClusterIP
  ports:
  - name: memcache
    port: 11211
    targetPort: memcache
    # nodePort: null
  selector:
    app.kubernetes.io/instance: memcached
    app.kubernetes.io/name: memcached
---
# Source: memcached/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  namespace: default
  labels:
    app.kubernetes.io/instance: memcached
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcached
    app.kubernetes.io/version: 1.6.22
    helm.sh/chart: memcached-6.7.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: memcached
      app.kubernetes.io/name: memcached
  replicas: 2
  podManagementPolicy: "Parallel"
  serviceName: memcached
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: memcached
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: memcached
        app.kubernetes.io/version: 1.6.22
        helm.sh/chart: memcached-6.7.1
        # annotations:
    spec:

      affinity:
        podAffinity:

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: memcached
                  app.kubernetes.io/name: memcached
              topologyKey: kubernetes.io/hostname
            weight: 1
        nodeAffinity:

      securityContext:
        fsGroup: 1001
      serviceAccountName: default
      containers:
      - name: memcached
        image: docker.io/bitnami/memcached:1.6.22-debian-11-r1
        imagePullPolicy: "IfNotPresent"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MEMCACHED_PORT_NUMBER
          value: "11211"
        ports:
        - name: memcache
          containerPort: 11211
        livenessProbe:
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          tcpSocket:
            port: memcache
        readinessProbe:
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
          tcpSocket:
            port: memcache
        resources:
          limits: {}
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
