apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
spec:
  type: NodePort
  ports:
    - port: 5678
      targetPort: 5678
      nodePort: 30048
      protocol: TCP
  selector:
    service: n8n