- name: k8s-all
  hosts: k8s_all
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
    - ./vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ var.k8s_all.tasks }}"
      when: var.k8s_all.tasks

- name: k8s-cp
  hosts: k8s_cp
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
    - ./vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ var.k8s_cp.tasks }}"
      when: var.k8s_cp.tasks

- name: k8s-cp-join
  hosts: k8s_cp_join
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
    - ./vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ var.k8s_cp_join.tasks }}"
      when: var.k8s_cp_join.tasks

- name: k8s-wk-master
  hosts: k8s_wk_master
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
    - ./vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ var.k8s_wk_master.tasks }}"
      when: var.k8s_wk_master.tasks

- name: k8s-wk-backup
  hosts: k8s_wk_backup
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
    - ./vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ var.k8s_wk_backup.tasks }}"
      when: var.k8s_wk_backup.tasks

- name: k8s-wk
  hosts: k8s_wk
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  vars_files:
    - ./env.yml
    - ./vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ var.k8s_wk.tasks }}"
      when: var.k8s_wk.tasks