- name: shell
  shell: helm repo add argo https://argoproj.github.io/argo-helm

- name: copy
  copy:
    src: ./files/secrets/argocd_secret.yaml
    dest: ~/
    owner: root
    group: root
    mode: '0644'
  ignore_errors: yes

- name: shell
  shell: kubectl create ns argocd && kubectl apply -f ~/argocd_secret.yaml

- name: copy
  copy:
    src: ./files/cp/argocd-apps-helm-chart-values.yaml
    dest: ~/
    owner: root
    group: root
    mode: '0644'
  ignore_errors: yes

- name: copy
  copy:
    src: ./files/cp/argocd-helm-chart-values.yaml
    dest: ~/
    owner: root
    group: root
    mode: '0644'
  ignore_errors: yes

- name: Execute helm
  shell: |
    helm install argocd argo/argo-cd \
        --version 5.51.4 \
        --create-namespace \
        --namespace argocd \
        --values ~/argocd-helm-chart-values.yaml
  register: result
  changed_when: false
- name: Show stdout helm
  debug:
    msg: "{{ result.stdout_lines }}"
  ignore_errors: true

- name: Execute helm
  shell: |
    helm install argocd argo/argocd-apps \
        --version 1.4.1 \
        --values ~/argocd-apps-helm-chart-values.yaml
  register: result
  changed_when: false
- name: Show stdout helm
  debug:
    msg: "{{ result.stdout_lines }}"
  ignore_errors: true

- name: mv yaml
  shell: mv ~/*.yaml ~/work
