- name: apt
  apt:
    name:
    - haproxy
    - keepalived

- name: copy
  copy:
    src: ./files/redundant/cp/haproxy.cfg
    dest: /etc/haproxy/
    mode: '0644'
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/haproxy/haproxy.cfg
    regexp: '\$\{KUBE_API_SERVER_VIP\}'
    replace: "{{ KUBE_API_SERVER_VIP }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/haproxy/haproxy.cfg
    regexp: '\$\{NODE_IPS\[0\]\}'
    replace: "{{ NODE_IPS_1 }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/haproxy/haproxy.cfg
    regexp: '\$\{NODE_IPS\[1\]\}'
    replace: "{{ NODE_IPS_2 }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/haproxy/haproxy.cfg
    regexp: '\$\{NODE_IPS\[2\]\}'
    replace: "{{ NODE_IPS_3 }}"
  ignore_errors: yes

- name: shell
  shell: echo "net.ipv4.ip_nonlocal_bind = 1" >> /etc/sysctl.conf

- name: shell
  shell: sysctl -p

- name: copy
  copy:
    src: ./files/redundant/cp/keepalived.conf
    dest: /etc/keepalived/
    mode: '0644'
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/keepalived/keepalived.conf
    regexp: '\$\{KUBE_API_SERVER_VIP\}'
    replace: "{{ KUBE_API_SERVER_VIP }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/keepalived/keepalived.conf
    regexp: '\$\{NODE_IPS\[0\]\}'
    replace: "{{ NODE_IPS_1 }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/keepalived/keepalived.conf
    regexp: '\$\{NODE_IPS\[1\]\}'
    replace: "{{ NODE_IPS_2 }}"
  ignore_errors: yes

- name: replace
  replace:
    path: /etc/keepalived/keepalived.conf
    regexp: '\$\{NODE_IPS\[2\]\}'
    replace: "{{ NODE_IPS_3 }}"
  ignore_errors: yes

- name: systemd
  systemd:
    name: keepalived
    state: restarted
    enabled: true
  ignore_errors: yes

- name: systemd
  systemd:
    name: haproxy
    state: restarted
    enabled: true
  ignore_errors: yes
